// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aa: typeof import('./../../src/components/aa.tsx')['default']
    Bb: typeof import('./../../src/pages/help/components/bb.tsx')['default']
  }
}

export { }
