// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ILucideCloudy: typeof import('~icons/lucide/cloudy')['default']
    'IWpf:fingerprintScan': typeof import('~icons/wpf/fingerprint-scan')['default']
    IWpfFullTrash: typeof import('~icons/wpf/full-trash')['default']
    OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
  }
}

export { }
